import React, { useEffect, useState } from "react";
import {
    Box,
    Paper,
    Typography,
    CircularProgress,
    Chip,
    Button,
    Dialog,
    DialogTitle,
    DialogContent,
    IconButton,
    TableCell,
    TableBody,
    TableRow,
    Table,
    TableHead,
    TableContainer
} from "@mui/material";

import {
    History as HistoryIcon,
    Visibility as VisibilityIcon,
    Close as CloseIcon
} from "@mui/icons-material";

import { BOOKINGS_API, FILES_BASE_URL } from "../../src/utils/api";

const CAReportHistory = () => {

    const [pdfOpen, setPdfOpen] = useState(false);

    const [selectedPdf, setSelectedPdf] = useState("");

    const [loading, setLoading] =
        useState(true);

    const [rows, setRows] =
        useState([]);

    useEffect(() => {

        fetchHistory();

    }, []);

    const fetchHistory = async () => {

        try {

            const response =
                await fetch(
                    `${BOOKINGS_API}/ca-report-history`,
                    {
                        headers: {
                            Authorization:
                                `Bearer ${localStorage.getItem("authToken")}`
                        }
                    }
                );

            const data =
                await response.json();

            setRows(
                data.data || []
            );

        } catch (err) {

            console.log(err);

        } finally {

            setLoading(false);
        }
    };

    const handleViewPdf = (pdfPath) => {

        setSelectedPdf(
            `${FILES_BASE_URL}${pdfPath}`
        );

        setPdfOpen(true);
    };

    const formatDate = (date) => {

        if (!date) return "-";

        return new Date(date)
            .toLocaleDateString(
                "en-GB"
            );
    };

    if (loading) {

        return (
            <Box
                sx={{
                    display: "flex",
                    justifyContent: "center",
                    mt: 5
                }}
            >
                <CircularProgress />
            </Box>
        );
    }

    return (

        <Paper
            elevation={0}
            sx={{
                p: 3,
                borderRadius: 4,
                background: "#fff",
                border: "1px solid",
                borderColor: "grey.100",
                boxShadow:
                    "0 10px 40px rgba(0,0,0,0.08)"
            }}
        >

            <Box
                sx={{
                    display: "flex",
                    alignItems: "center",
                    gap: 2,
                    mb: 3
                }}
            >

                <HistoryIcon
                    color="primary"
                    sx={{ fontSize: 35 }}
                />

                <Box>

                    <Typography
                        variant="h5"
                        fontWeight={700}
                    >
                        CA Report History
                    </Typography>

                    <Typography
                        variant="body2"
                        color="text.secondary"
                    >
                        Downloaded CA Reports
                    </Typography>

                </Box>

            </Box>

            <TableContainer>

                <Table>

                    <TableHead>

                        <TableRow>

                            <TableCell>
                                Report No
                            </TableCell>

                            <TableCell>
                                Months
                            </TableCell>

                            <TableCell>
                                SAC Code
                            </TableCell>

                            <TableCell>
                                From Date
                            </TableCell>

                            <TableCell>
                                To Date
                            </TableCell>

                            <TableCell>
                                Records
                            </TableCell>

                            <TableCell>
                                Generated By
                            </TableCell>

                            <TableCell>
                                Generated On
                            </TableCell>
                            <TableCell>
                                Action
                            </TableCell>

                        </TableRow>

                    </TableHead>

                    <TableBody>

                        {
                            rows.map(
                                (row) => (

                                    <TableRow
                                        key={row._id}
                                    >

                                        <TableCell>

                                            <Chip
                                                label={
                                                    row.reportNumber
                                                }
                                                color="primary"
                                            />

                                        </TableCell>

                                        <TableCell>
                                            {
                                                row.months
                                            }
                                        </TableCell>

                                        <TableCell>
                                            {row.sacCode || "9968"}
                                        </TableCell>

                                        <TableCell>
                                            {
                                                formatDate(
                                                    row.fromDate
                                                )
                                            }
                                        </TableCell>

                                        <TableCell>
                                            {
                                                formatDate(
                                                    row.toDate
                                                )
                                            }
                                        </TableCell>

                                        <TableCell>
                                            {
                                                row.totalRecords
                                            }
                                        </TableCell>

                                        <TableCell>

                                            {
                                                row.downloadedBy
                                                    ?.firstName
                                            }{" "}

                                            {
                                                row.downloadedBy
                                                    ?.lastName
                                            }

                                        </TableCell>

                                        <TableCell>
                                            {
                                                formatDate(
                                                    row.createdAt
                                                )
                                            }
                                        </TableCell>
                                        <TableCell>

                                            <Box
                                                sx={{
                                                    display: "flex",
                                                    gap: 1
                                                }}
                                            >

                                                <Button
                                                    variant="contained"
                                                    color="primary"
                                                    startIcon={<VisibilityIcon />}
                                                    size="small"
                                                    onClick={() =>
                                                        handleViewPdf(
                                                            row.pdfPath
                                                        )
                                                    }
                                                >
                                                    View
                                                </Button>

                                                <Button
                                                    variant="contained"
                                                    color="success"
                                                    size="small"
                                                    onClick={() =>
                                                        window.open(
                                                            `${FILES_BASE_URL}${row.excelPath}`,
                                                            "_blank"
                                                        )
                                                    }
                                                >
                                                    Excel
                                                </Button>

                                            </Box>

                                        </TableCell>

                                    </TableRow>
                                )
                            )
                        }

                    </TableBody>

                </Table>

            </TableContainer>
            <Dialog
                open={pdfOpen}
                onClose={() =>
                    setPdfOpen(false)
                }
                fullScreen
            >

                <DialogTitle
                    sx={{
                        display: "flex",
                        justifyContent:
                            "space-between",
                        alignItems: "center"
                    }}
                >

                    CA Report Preview

                    <IconButton
                        onClick={() =>
                            setPdfOpen(false)
                        }
                    >
                        <CloseIcon />
                    </IconButton>

                </DialogTitle>

                <DialogContent
                    sx={{
                        p: 0
                    }}
                >

                    <iframe
                        src={selectedPdf}
                        width="100%"
                        height="100%"
                        style={{
                            border: "none",
                            minHeight: "90vh"
                        }}
                        title="CA Report"
                    />

                </DialogContent>

            </Dialog>
        </Paper>
    );
};

export default CAReportHistory;