import React, { useEffect, useState } from "react";
import {
    Paper,
    Typography,
    Table,
    TableBody,
    TableCell,
    TableContainer,
    TableHead,
    TableRow,
    CircularProgress,
    Chip,
    Box,
    Button
} from "@mui/material";

import { BOOKINGS_API, FILES_BASE_URL } from "../../src/utils/api";

const CAReportHistory = () => {

    const [loading, setLoading] =
        useState(true);

    const [rows, setRows] =
        useState([]);

    useEffect(() => {

        fetchHistory();

    }, []);

    const fetchHistory = async () => {

        try {

            const response =
                await fetch(
                    `${BOOKINGS_API}/ca-report-history`,
                    {
                        headers: {
                            Authorization:
                                `Bearer ${localStorage.getItem("authToken")}`
                        }
                    }
                );

            const data =
                await response.json();

            setRows(
                data.data || []
            );

        } catch (err) {

            console.log(err);

        } finally {

            setLoading(false);
        }
    };

    const formatDate = (date) => {

        if (!date) return "-";

        return new Date(date)
            .toLocaleDateString(
                "en-GB"
            );
    };

    if (loading) {

        return (
            <Box
                sx={{
                    display: "flex",
                    justifyContent: "center",
                    mt: 5
                }}
            >
                <CircularProgress />
            </Box>
        );
    }

    return (

        <Paper
            sx={{
                p: 3,
                borderRadius: 3
            }}
        >

            <Typography
                variant="h5"
                fontWeight={700}
                mb={3}
            >
                CA Report History
            </Typography>

            <TableContainer>

                <Table>

                    <TableHead>

                        <TableRow>

                            <TableCell>
                                Report No
                            </TableCell>

                            <TableCell>
                                Months
                            </TableCell>

                            <TableCell>
                                From Date
                            </TableCell>

                            <TableCell>
                                To Date
                            </TableCell>

                            <TableCell>
                                Records
                            </TableCell>

                            <TableCell>
                                Generated By
                            </TableCell>

                            <TableCell>
                                Generated On
                            </TableCell>
                            <TableCell>
                                Action
                            </TableCell>

                        </TableRow>

                    </TableHead>

                    <TableBody>

                        {
                            rows.map(
                                (row) => (

                                    <TableRow
                                        key={row._id}
                                    >

                                        <TableCell>

                                            <Chip
                                                label={
                                                    row.reportNumber
                                                }
                                                color="primary"
                                            />

                                        </TableCell>

                                        <TableCell>
                                            {
                                                row.months
                                            }
                                        </TableCell>

                                        <TableCell>
                                            {
                                                formatDate(
                                                    row.fromDate
                                                )
                                            }
                                        </TableCell>

                                        <TableCell>
                                            {
                                                formatDate(
                                                    row.toDate
                                                )
                                            }
                                        </TableCell>

                                        <TableCell>
                                            {
                                                row.totalRecords
                                            }
                                        </TableCell>

                                        <TableCell>

                                            {
                                                row.downloadedBy
                                                    ?.firstName
                                            }{" "}

                                            {
                                                row.downloadedBy
                                                    ?.lastName
                                            }

                                        </TableCell>

                                        <TableCell>
                                            {
                                                formatDate(
                                                    row.createdAt
                                                )
                                            }
                                        </TableCell>
                                        <TableCell>

                                            <Button
                                                variant="contained"
                                                size="small"
                                                onClick={() =>
                                                    window.open(
                                                        `${FILES_BASE_URL}${row.pdfPath}`,
                                                        "_blank"
                                                    )
                                                }
                                            >
                                                View
                                            </Button>

                                        </TableCell>

                                    </TableRow>
                                )
                            )
                        }

                    </TableBody>

                </Table>

            </TableContainer>

        </Paper>
    );
};

export default CAReportHistory;